In [1]:
#It is a good code for recorning the video For Real

In [2]:
%matplotlib inline
import numpy as np
import cv2
import random
import datetime as dt
import tensorflow as tf
from collections import deque
import matplotlib.pyplot as plt
from tensorflow.keras.layers import *
from tensorflow.keras.models import Sequential
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.callbacks import EarlyStopping
from tensorflow.keras.utils import plot_model

In [3]:
#Parameters
record = 1 # on=1 off=0
namerec = "sequence30-NTD10-K1-LSTM"

In [4]:
import pandas as pd

# Load the Excel file into a DataFrame
df = pd.read_excel(r'F:\Courses\Paper\Mine\Paper3\Animation\For recording\Properties-Part1.xlsx', sheet_name='Sheet1')

# Select the values from row 3 and onwards
Properties = df.values[1:]

In [5]:
import numpy as np

# Assume the data array is already loaded into a variable named 'data'

# Find the indices where the values are "N" or "F"
idx_n = np.where(Properties == np.array(["N"], dtype=str))
idx_f = np.where(Properties == np.array(["F"], dtype=str))

# Replace "N" with "1"
Properties[idx_n] = 1

# Replace "F" with "2"
Properties[idx_f] = 2


In [6]:
Properties = np.array(Properties)
Properties = Properties.astype(float)

In [7]:
resulotion = 1/30
Dim = round((Properties[-1,0]-Properties[0,0])/resulotion)
Properties_res = np.zeros((Dim, Properties.shape[1]))
t0 = 0
tf = 303
t = t0
Properties_inter = 0

for i in range(Dim):
    Properties_res[i] = Properties[Properties_inter]
    Properties_res[i,0] = t
    if t >= Properties[Properties_inter+1,0]:
        Properties_inter += 1
    
    t += resulotion

In [8]:
Properties_res = np.array(Properties_res[:,1:19])

In [9]:
Properties_res.shape

(9090, 18)

In [10]:
sequence = 30
Model_data_normal_sequence = np.zeros((Properties_res.shape[0],sequence,Properties_res.shape[1]),dtype='float')
inter = 0
for i in range(Model_data_normal_sequence.shape[0]-sequence):
    for j in range(sequence):
        Model_data_normal_sequence[inter,j] = Properties_res[i+j]
    inter += 1
        
Model_data_normal_sequence = np.array(Model_data_normal_sequence[0:inter])

In [11]:
import tensorflow as tf
from tensorflow import keras
import h5py

# Load the model from the HDF5 file
loaded_model = keras.models.load_model(r'F:\Courses\Paper\Mine\Paper3\Results\LSTM-K2-TTP0.8-sequence30.h5')

In [12]:
y_pred = loaded_model.predict(Model_data_normal_sequence)


284/284 [==============================] - 5s 10ms/step


In [13]:
Model_data_normal_sequence[0,-1]

array([  1.,   1.,   7.,   0.,   0., -75.,   1.,   2.,   7.,   0.,   0.,
        60.,   0.,   0.,   0.,   0.,   0.,   0.])

In [14]:
y_pred[0]

array([0.5290264 , 0.47017723, 0.0007964 ], dtype=float32)

In [15]:
#y_pred = model.predict(X_train)
y_pred = loaded_model.predict(Model_data_normal_sequence)
Label = np.zeros(y_pred.shape[0],dtype='int') 
for i in range(Label.shape[0]):
    a=y_pred[i]
    a=a.argmax()
    if Model_data_normal_sequence[250*30,-1,6*a]==0:
        y_pred[i,a]=0
        a=y_pred[i]
        a=a.argmax()
    Label[i] = a 

284/284 [==============================] - 3s 11ms/step


In [16]:
mylist = ['Number 1',
          'Number 2',
          'Number 3']

In [17]:
Properties_res[100]

array([  1.,   1.,   7.,   0.,   0., -45.,   1.,   2.,   7.,   0.,   0.,
        30.,   0.,   0.,   0.,   0.,   0.,   0.])

In [18]:
from scipy.stats import multivariate_normal

def Star(Object,i):
    max_rep = 0
    multipy = 100  #50
    power = 2 #2
    XX = 0
    YY = 0

    if Object =='Number 1':
        if Properties_res[i,1]==1:
            if Properties_res[i,2]!=7 and Properties_res[i,2]!=2:
                max_rep = 0
                #max_rep = 6
                #XX = int(5.5*Properties_res[i,5]+512.5)
                #YY = int(415)
                Mean1N = np.array([265, 415])
                cov1N = np.array([[440, 73],[73, 730]])
                while max_rep<5:
                    x, y = np.random.multivariate_normal(Mean1N, cov1N, 1).T
                    var = multivariate_normal(mean=Mean1N, cov=cov1N)
                    max_rep = round((var.pdf(np.array([x[0],y[0]]))/var.pdf(Mean1N))**power*multipy)
                    XX = round(x[0])
                    YY = round(y[0])
            else:
                XX = int(5.5*Properties_res[i,5]+512.5)
                YY = int(415)

        else:
            if Properties_res[i,2]!=7 and Properties_res[i,2]!=2:
                max_rep = 0
                Mean1F = np.array([420, 435])
                cov1F = np.array([[232, 28],[28, 534]])
                while max_rep<5:
                    x, y = np.random.multivariate_normal(Mean1F, cov1F, 1).T
                    var = multivariate_normal(mean=Mean1F, cov=cov1F)
                    max_rep = round((var.pdf(np.array([x[0],y[0]]))/var.pdf(Mean1F))**power*multipy)
                    XX = round(x[0])
                    YY = round(y[0])
            else:
                XX = int(10.66*Properties_res[i,5]+740)
                YY = int(435)
           
            
    elif Object =='Number 2':
        if Properties_res[i,7]==1:
            if Properties_res[i,8]!=7 and Properties_res[i,8]!=2:
                max_rep = 0
                Mean2N = np.array([930, 415])
                cov2N = np.array([[442, 34],[34, 447]])
                while max_rep<5:
                    x, y = np.random.multivariate_normal(Mean2N, cov2N, 1).T
                    var = multivariate_normal(mean=Mean2N, cov=cov2N)
                    max_rep = round((var.pdf(np.array([x[0],y[0]]))/var.pdf(Mean2N))**power*multipy)
                    XX = round(x[0])
                    YY = round(y[0])
            else:
                XX = int(11.06*Properties_res[i,11]+930)
                YY = int(415)
        else:                       
            if Properties_res[i,8]!=7 and Properties_res[i,8]!=2:
                max_rep = 0
                Mean2F = np.array([940, 435])
                cov2F = np.array([[216, 48],[48, 464]])
                while max_rep<5:
                    x, y = np.random.multivariate_normal(Mean2F, cov2F, 1).T
                    var = multivariate_normal(mean=Mean2F, cov=cov2F)
                    max_rep = round((var.pdf(np.array([x[0],y[0]]))/var.pdf(Mean2F))**power*multipy)
                    XX = round(x[0])
                    YY = round(y[0])
            else:
                XX = int(14.66*Properties_res[i,11]+940)
                YY = int(435)
                
                    
    elif Object =='Number 3':
        if Properties_res[i,12]==1:
            if Properties_res[i,13]!=7 and Properties_res[i,13]!=2:
                max_rep = 0
                Mean3N = np.array([1600, 415])
                cov3N = np.array([[440, 73],[73, 730]])
                while max_rep<5:
                    x, y = np.random.multivariate_normal(Mean3N, cov3N, 1).T
                    var = multivariate_normal(mean=Mean3N, cov=cov3N)
                    max_rep = round((var.pdf(np.array([x[0],y[0]]))/var.pdf(Mean3N))**power*multipy)
                    XX = round(x[0])
                    YY = round(y[0])
                
            else:
                XX = int(7.33*Properties_res[i,17]+1270)
                YY = int(415)
                
        else:
            if Properties_res[i,12]!=7 and Properties_res[i,12]!=2:
                max_rep = 0
                Mean3F = np.array([1500, 435])
                cov3F = np.array([[232, 28],[28, 534]])
                while max_rep<5:
                    x, y = np.random.multivariate_normal(Mean3F, cov3F, 1).T
                    var = multivariate_normal(mean=Mean3F, cov=cov3F)
                    max_rep = round((var.pdf(np.array([x[0],y[0]]))/var.pdf(Mean3F))**power*multipy)
                    XX = round(x[0])
                    YY = round(y[0])
            else:
                XX = int(10.66*Properties_res[i,17]+1180)
                YY = int(435)

    return XX,YY, max_rep
            
            

In [19]:
cap = cv2.VideoCapture(r'F:\Courses\Paper\Mine\Paper3\Animation\For recording\Animation-Part 1.mkv')

record = 1
delta = 1

width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH) + 0.5)
height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT) + 0.5)
size = (width, height)
if record == 1:
    fourcc = cv2.VideoWriter_fourcc(*'XVID')
    out = cv2.VideoWriter(r"F:\Courses\Paper\Mine\Paper3/"+namerec+".avi", fourcc, 30.0, size)

    
#Parameters    
i = 0
w = 0
counter = 0
max_rep = 0
str_count = "Hi"
XX_old = 1920/2
YY_old = 900

while(cap.isOpened()):
    
    #For python
    ret, frame = cap.read()
    if ret == False or i==30*5*60:
        break
        
    cv2.namedWindow("frame", cv2.WINDOW_NORMAL)        # Create window with freedom of dimensions
    cv2.resizeWindow("frame", 2000, 800)
    rgb_frame = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

    #For time
    cv2.putText(frame,"t="+str(round(i/30,2))+"s", (100,100), cv2.FONT_HERSHEY_SIMPLEX, 1,(255,255,255),2)


    #For detect
    if i >= sequence:
        #Update after delta
        if i%delta == 0: 
            A = Label[w]
            w = w + 1

        if str_count != mylist[A] or counter >= max_rep:
            str_count = mylist[A]
            XX, YY, max_rep = Star(mylist[A],i) 
            counter = 0
        else:
            counter = counter + 1

    else:
        XX = int(XX_old)
        YY = int(YY_old)

    XX_draw = int(XX_old + (XX - XX_old)/10)
    YY_draw = int(YY_old + (YY - YY_old)/10)

    XX_old = XX_draw
    YY_old = YY_draw


    cv2.putText(frame, "*", (XX_draw, YY_draw), cv2.FONT_HERSHEY_SIMPLEX, 1,(255,255,255),2) #Detecter Model


    if record==1:
        out.write(frame)

    cv2.imshow('frame', frame)
    
    i += 1
    if cv2.waitKey(1) & 0xFF == ord('q'):
        break
    cv2.waitKey(1)
    
    
cap.release()
cv2.destroyAllWindows()

In [20]:
cap.release()
out.release()
cv2.destroyAllWindows()

In [21]:
# for i in Label:
#     print(i)

In [22]:
Label[0]

0

In [23]:
Star("Number 1",31)

(100, 415, 0)

In [24]:
Properties_res[31]

array([  1.,   1.,   7.,   0.,   0., -75.,   1.,   2.,   7.,   0.,   0.,
        60.,   0.,   0.,   0.,   0.,   0.,   0.])

In [25]:
Mean1N = np.array([265, 415])
cov1N = np.array([[440, 34],[34, 730]])
x, y = np.random.multivariate_normal(Mean1N, cov1N, 1).T
var = multivariate_normal(mean=Mean1N, cov=cov1N)
max_rep = round((var.pdf(np.array([x[0],y[0]]))/var.pdf(Mean1N))**power*multipy)

NameError: name 'power' is not defined

In [ ]:
x

In [ ]:
Properties_res[i]

In [ ]:
i

In [ ]:
Label[250*30]

In [ ]:
y_pred[250*30]

In [ ]:
Model_data_normal_sequence[250*30,-1]

In [ ]:
if Model_data_normal_sequence[250*30,-1]

In [ ]:
a=y_pred[250*30]
a=a.argmax()
if Model_data_normal_sequence[250*30,-1,6*a]==0:
    y_pred[250*30,a]=0
    a=y_pred[250*30]
    a=a.argmax()

In [ ]:
Model_data_normal_sequence[250*30,-1,6*a]==0